server:
  port: 800
  address: 0.0.0.0

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/community1
    username: community1
    password: g383wE

  security:
    user:
      name: admin
      password: admin


mybatis:
  mapper-locations:
    - /mapper/*.xml

