server:
  port: 80
  address: 0.0.0.0

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.citk838y6vgk.ap-northeast-2.rds.amazonaws.com:3306/community1
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: admin


mybatis:
  mapper-locations:
    - /mapper/*.xml
